from enum import Enum

class DriftCategory(str, Enum):
    REQUIREMENT_DRIFT = "REQUIREMENT_DRIFT"
    DEPENDENCY_DRIFT = "DEPENDENCY_DRIFT"
    API_DRIFT = "API_DRIFT"
    INFRASTRUCTURE_DRIFT = "INFRASTRUCTURE_DRIFT"
    SECURITY_DRIFT = "SECURITY_DRIFT"
    PERFORMANCE_DRIFT = "PERFORMANCE_DRIFT"
    DOCUMENTATION_DRIFT = "DOCUMENTATION_DRIFT"
    CONSTRAINT_DRIFT = "CONSTRAINT_DRIFT"
    ADVERSARIAL_DRIFT = "ADVERSARIAL_DRIFT"

class DriftSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
